<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class ApiWebview extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('m_api','model');
       
        
    }

    function index()
    {
        echo "on";
    }
   function getDataPelayananPesertaBaru()
    {
        $data['data']   = $this->model->getDataRegisterLayananBaru();
        $data['judul'] = "Data Jumlah Peserta Pelayanan KB Baru";
        $data['link'] = "apiWebview/getDataPelayananPesertaBaruXls";
        // $this->load->view('jumlahkkgrafik/webview_peserta_baru',$data);
        $this->load->view('jumlahkkgrafik/webview_peserta_baru_grafik',$data);

    }

    function getDataPelayananPesertaBaruXls()
    {
        $data['data']   = $this->model->getDataRegisterLayananBaru();
        $data['judul'] = "Data Jumlah Peserta Pelayanan KB Baru";



        $this->load->view('jumlahkkgrafik/webview_peserta_baru_grafik_xls',$data);

    }

    function getDataPelayananPesertaAktif()
    {
        $data['data']   = $this->model->getDataRegisterLayananAktif();
        $data['judul'] = "Data Jumlah Peserta Pelayanan KB Aktif";
        $data['link'] = "apiWebview/getDataPelayananPesertaAktifXls";
        $this->load->view('jumlahkkgrafik/webview_peserta_baru_grafik',$data);

    }
     function getDataPelayananPesertaAktifXls()
    {
        $data['data']   = $this->model->getDataRegisterLayananAktif();
        $data['judul'] = "Data Jumlah Peserta Pelayanan KB Aktif";
        $this->load->view('jumlahkkgrafik/webview_peserta_baru_grafik_xls',$data);

    }

    function infoStokAlatKB()
    {
        $data['data']   = $this->model->stokAlatKontrasepsi();
        $data['judul'] = "Data Jumlah Stok Alat Kontrasepsi";
        $this->load->view('jumlahkkgrafik/webview_stok_alat_kontrasepsi',$data);

    }

}
