 <?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Indikatortahunan extends CI_Controller{
    function __construct()
    {
        parent::__construct(); 
        if (!$this->session->userdata('login')) {
            redirect('login','index');
        }
        $this->load->model('M_indikator');
    } 

    /*
     * Listing of image_slider
     */
    function index()
    {

        $data['image_slider'] = $this->M_indikator->get_all_indikator_tahunan();
        
        $data['_view'] = 'indikator_tahunan/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new image_banner
     */
    function add()
    {   
        $this->load->library('form_validation');

        $this->form_validation->set_rules('nama_file','Nama File','required');
        
        if($this->form_validation->run())     
        {   
                 $image = time().'-'.str_replace(' ', '_', $_FILES["userfile"]['name']);


                $config = array(
                    'upload_path' => "./upload/file/",
                    'overwrite' => TRUE,
                    'max_size' => "99999999999",
                    'file_name' => $image,
                    'allowed_types' => "xls"
                    );
                    $this->load->library('upload', $config);

                if ( ! $this->upload->do_upload('userfile'))
                {
                        $error = array('error' => $this->upload->display_errors());
                        $this->session->set_flashdata('Message',$error);
                        $data['_view'] = 'indikator_tahunan/add'; 
                        $this->load->view('layouts/main',$data);
                }
                else
                {
                        $data = array('upload_data' => $this->upload->data());
                        $params = array(
                            'link' => base_url()."upload/file/".$image,
                            'nama_file' => $this->input->post('nama_file'),
                            'created_at' => date('Y-m-d H:i:s'),
                            'created_by' => $this->session->userdata('admin_id'),
                            'tipe' => 'tahunan'
                        );
                        
                        $image_banner_id = $this->M_indikator->add_indikator($params);
                        redirect('indikatortahunan/index');

                }
        }
        else
        {            
          

            $data['count_data'] = $this->M_indikator->get_all_indikator_tahunan();
            $data['_view'] = 'indikator_tahunan/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a image_banner
     */
    function edit($slider_id)
    {   
        // check if the image_banner exists before trying to edit it
        $data['image_banner'] = $this->M_indikator->get_indikator($slider_id);

        
        if(isset($data['image_banner']['id_laporan']))
        {

            if(isset($_POST) && count($_POST) > 0)     
            {   


                if(trim($_FILES["userfile"]['name']) != "")
                {

                         $image = time().'-'.str_replace(' ', '_', $_FILES["userfile"]['name']);

                            $config = array(
                                'upload_path' => "./upload/file/",
                                'allowed_types' => "xls",
                                'overwrite' => TRUE,
                                'max_size' => "99999999999",
                                'file_name' => $image
                                );
                                $this->load->library('upload', $config);

                            if ( ! $this->upload->do_upload('userfile'))
                            {
                                    $error = array('error' => $this->upload->display_errors());
                                    $this->session->set_flashdata('Message',$error);
                                    $data['_view'] = 'indikator_tahunan/edit';
                                    $this->load->view('layouts/main',$data);
                            }
                            else
                            {
                                    $data = array('upload_data' => $this->upload->data());
                                    $params = array(
                                        'link' => base_url()."upload/file/".$image,
                                        'nama_file' => $this->input->post('nama_file')
                                    );
                                    
                                $this->M_indikator->update_indikator($slider_id,$params);            
                                redirect('indikatortahunan/index');

                            }

                }else
                {
                   $params = array(
                        'created_by' => $this->session->userdata('admin_id'),
                                        'nama_file' => $this->input->post('nama_file')
                    ); 
                    $this->M_indikator->update_indikator($slider_id,$params);            
                    redirect('indikatortahunan/index');
                }


                

            }
            else
            {
                $data['_view'] = 'indikator_tahunan/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The image_banner you are trying to edit does not exist.');
    } 

    /*
     * Deleting image_banner
     */
    function remove($slider_id)
    {
        $image_banner = $this->M_indikator->get_indikator($slider_id);

        // check if the image_banner exists before trying to delete it
        if(isset($image_banner['id_laporan']))
        {
            $this->M_indikator->delete_indikator($slider_id);
            redirect('indikatortahunan/index');
        }
        else
            show_error('The image_banner you are trying to delete does not exist.');
    }
    
}
