<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Levelakses extends CI_Controller{
    function __construct()
    {
        parent::__construct(); 
        if (!$this->session->userdata('login')) {
            redirect('login','index');
        }
        $this->load->model('M_levelakses');
    } 

    /*
     * Listing of mstlevel_akses
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('levelakses/index?');
        $config['total_rows'] = $this->M_levelakses->get_all_mstlevel_akses_count();
        $this->pagination->initialize($config);

        $data['mstlevel_akses'] = $this->M_levelakses->get_all_mstlevel_akses($params);
        
        $data['_view'] = 'level_akse/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new level_akses
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama_level','Nama Level','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nama_level' => $this->input->post('nama_level'),
            );
            
            $level_akses_id = $this->M_levelakses->add_level_akses($params);
            redirect('levelakses/index');
        }
        else
        {            
            $data['_view'] = 'level_akse/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a level_akses
     */
    function edit($level_id)
    {   
        // check if the level_akses exists before trying to edit it
        $data['level_akses'] = $this->M_levelakses->get_level_akses($level_id);
        
        if(isset($data['level_akses']['level_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nama_level','Nama Level','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nama_level' => $this->input->post('nama_level'),
                );

                $this->M_levelakses->update_level_akses($level_id,$params);            
                redirect('levelakses/index');
            }
            else
            {
                $data['_view'] = 'level_akse/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The level_akses you are trying to edit does not exist.');
    } 

    /*
     * Deleting level_akses
     */
    function remove($level_id)
    {
        $level_akses = $this->M_levelakses->get_level_akses($level_id);

        // check if the level_akses exists before trying to delete it
        if(isset($level_akses['level_id']))
        {
            $this->M_levelakses->delete_level_akses($level_id);
            redirect('levelakses/index');
        }
        else
            show_error('The level_akses you are trying to delete does not exist.');
    }
    
}
