<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
defined('BASEPATH') OR exit('No direct script access allowed');
class Mstmenu extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        if (!$this->session->userdata('login')) {
            redirect('login','index');
        }
        
        $this->load->model('Mstmenu_model');
    } 

    /*
     * Listing of mstmenu
     */
    function index()
    {
        $data['mstmenu'] = $this->Mstmenu_model->get_all_mstmenu();
        
        $data['_view'] = 'mstmenu/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new menu
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'parent_menu' => $this->input->post('parent_menu'),
				'menu_name' => $this->input->post('menu_name'),
				'script_menu' => $this->input->post('script_menu'),
				'menu_fas' => $this->input->post('menu_fas'),
				'active_status' => $this->input->post('active_status'),
            );
            
            $menu_id = $this->Mstmenu_model->add_menu($params);
            redirect('mstmenu/index');
        }
        else
        {			$data['all_mstmenu'] = $this->Mstmenu_model->get_all_mstmenu();
            $data['_view'] = 'mstmenu/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a menu
     */
    function edit($menu_id)
    {   
        // check if the menu exists before trying to edit it
        $data['menu'] = $this->Mstmenu_model->get_menu($menu_id);
        
        if(isset($data['menu']['menu_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'parent_menu' => $this->input->post('parent_menu'),
					'menu_name' => $this->input->post('menu_name'),
					'script_menu' => $this->input->post('script_menu'),
					'menu_fas' => $this->input->post('menu_fas'),
					'active_status' => $this->input->post('active_status'),
                );

                $this->Mstmenu_model->update_menu($menu_id,$params);            
                redirect('mstmenu/index');
            }
            else
            {			
                $data['all_mstmenu'] = $this->Mstmenu_model->get_all_mstmenu();
                $data['_view'] = 'mstmenu/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The menu you are trying to edit does not exist.');
    } 

    /*
     * Deleting menu
     */
    function remove($menu_id)
    {
        $menu = $this->Mstmenu_model->get_menu($menu_id);

        // check if the menu exists before trying to delete it
        if(isset($menu['menu_id']))
        {
            $this->Mstmenu_model->delete_menu($menu_id);
            redirect('mstmenu/index');
        }
        else
            show_error('The menu you are trying to delete does not exist.');
    }
    
}
