<?php 
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Msttipekb extends CI_Controller{
    function __construct()
    {
        parent::__construct(); 
        if (!$this->session->userdata('login')) {
            redirect('login','index');
        }
        $this->load->model('Msttipekb_model');
    } 

    /*
     * Listing of msttipekb
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('msttipekb/index?');
        $config['total_rows'] = $this->Msttipekb_model->get_all_msttipekb_count();
        $this->pagination->initialize($config);

        $data['msttipekb'] = $this->Msttipekb_model->get_all_msttipekb($params);
        
        $data['_view'] = 'msttipekb/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new jenis_kb
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama_tipe','Nama Tipe','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nama_tipe' => $this->input->post('nama_tipe'),
            );
            
            $jenis_kb_id = $this->Msttipekb_model->add_jenis_kb($params);
            redirect('msttipekb/index');
        }
        else
        {            
            $data['_view'] = 'msttipekb/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a jenis_kb
     */
    function edit($tipekb_id)
    {   
        // check if the jenis_kb exists before trying to edit it
        $data['jenis_kb'] = $this->Msttipekb_model->get_jenis_kb($tipekb_id);
        
        if(isset($data['jenis_kb']['tipekb_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nama_tipe','Nama Tipe','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nama_tipe' => $this->input->post('nama_tipe'),
                );

                $this->Msttipekb_model->update_jenis_kb($tipekb_id,$params);            
                redirect('msttipekb/index');
            }
            else
            {
                $data['_view'] = 'msttipekb/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The jenis_kb you are trying to edit does not exist.');
    } 

    /*
     * Deleting jenis_kb
     */
    function remove($tipekb_id)
    {
        $jenis_kb = $this->Msttipekb_model->get_jenis_kb($tipekb_id);

        // check if the jenis_kb exists before trying to delete it
        if(isset($jenis_kb['tipekb_id']))
        {
            $this->Msttipekb_model->delete_jenis_kb($tipekb_id);
            redirect('msttipekb/index');
        }
        else
            show_error('The jenis_kb you are trying to delete does not exist.');
    }
    
}
