<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
  
class Mstunit extends CI_Controller{
    function __construct()
    {
        parent::__construct(); 
        if (!$this->session->userdata('login')) {
            redirect('login','index');
        }
        $this->load->model('Mstunit_model');
    } 

    /*
     * Listing of mstunit
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('mstunit/index?');
        $config['total_rows'] = $this->Mstunit_model->get_all_mstunit_count();
        $this->pagination->initialize($config);

        $data['mstunit'] = $this->Mstunit_model->get_all_mstunit($params);
        
        $data['_view'] = 'mstunit/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new unit
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('unit_name','Unit Name','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'unit_name' => $this->input->post('unit_name'),
				'created_at' => date('Y-m-d H:i:s'),
            );
            
            $unit_id = $this->Mstunit_model->add_unit($params);
            redirect('mstunit/index');
        }
        else
        {            
            $data['_view'] = 'mstunit/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a unit
     */
    function edit($unit_id)
    {   
        // check if the unit exists before trying to edit it
        $data['unit'] = $this->Mstunit_model->get_unit($unit_id);
        
        if(isset($data['unit']['unit_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('unit_name','Unit Name','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'unit_name' => $this->input->post('unit_name'),
                    'created_at' => date('Y-m-d H:i:s'),
                );

                $this->Mstunit_model->update_unit($unit_id,$params);            
                redirect('mstunit/index');
            }
            else
            {
                $data['_view'] = 'mstunit/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The unit you are trying to edit does not exist.');
    } 

    /*
     * Deleting unit
     */
    function remove($unit_id)
    {
        $unit = $this->Mstunit_model->get_unit($unit_id);

        // check if the unit exists before trying to delete it
        if(isset($unit['unit_id']))
        {
            $this->Mstunit_model->delete_unit($unit_id);
            redirect('mstunit/index');
        }
        else
            show_error('The unit you are trying to delete does not exist.');
    }
    
}
