<?php
date_default_timezone_set("Asia/Jakarta");
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pesanmasuk extends CI_Controller{
    function __construct()
    {
        parent::__construct(); 
       
        $this->load->model('M_pesanmasuk');
    } 

    /*
     * Listing of dataperiode
     */
    function index()
    {
         if (!$this->session->userdata('login')) {
            redirect('login','index');
        }

         $data['record'] = $this->M_pesanmasuk->view_join('mst_pesan','mstuser','user_id','STATUS','ASC');
        
        $data['_view'] = 'pesanmasuk/index';
        $this->load->view('layouts/main',$data);
    }

  

    function detail_pesan_masuk($id_pesan)
    {

        if (!$this->session->userdata('login')) {
            redirect('login','index');
        }
        //$data['record'] = $this->M_pesanmasuk->view_where('mst_pesan',array('admin_id'=>$this->session->userdata('admin_id')));
        $data['record'] = $this->M_pesanmasuk->view_join_where('mst_pesan_detail','mstuser','user_id',array('id_pesan' => $id_pesan),'date_created','asc');


        $data['_view'] = 'pesanmasuk/pesandetail';
        $this->load->view('layouts/main',$data);
    }

    function balasPesan()
    {

            $data = array('admin_id'=>$this->session->userdata('admin_id'),
                          'id_pesan'=>$this->input->post('id_pesan'),
                          'date_created'=>date('Y-m-d H:i:s'),
                          'message'=>$this->input->post('message'),
                          'user_id'=>$this->input->post('user_id'),
                          'pesan_dari'=>'admin'
                      );

                        $this->M_pesanmasuk->insert('mst_pesan_detail',$data);


            $where = array('id_pesan' => $this->input->post('id_pesan'));
            $this->M_pesanmasuk->update('mst_pesan', array('STATUS'=> '1','created_date'=>date('Y-m-d H:i:s')), $where);

        $lastId =$this->M_pesanmasuk->view_join_where('mst_pesan_detail','mstuser','user_id',array('admin_id'=>$this->session->userdata('admin_id'),'mst_pesan_detail.user_id' => $this->input->post('user_id')),'date_created','asc');

        echo $lastId[count($lastId)-1]['id_pesan_detail'];
    }

    function ambilPesan()
    {


        $data = $this->M_pesanmasuk->getLastPesan($this->input->post('id_pesan'),$this->session->userdata('admin_id'),$this->input->post('user_id'),
                $this->input->post('id_pesan_detail_terakhir'));

        echo json_encode($data);

    }
    
}
