 <?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Stok_alat_kontrasepsi extends CI_Controller{
    function __construct()
    {
        parent::__construct(); 
        if (!$this->session->userdata('login')) {
            redirect('login','index');
        }
        $this->load->model('Stok_alat_kontrasepsi_model');
    } 

    /*
     * Listing of stok_alat_kontrasepsi
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('stok_alat_kontrasepsi/index?');
        $config['total_rows'] = $this->Stok_alat_kontrasepsi_model->get_all_stok_alat_kontrasepsi_count();
        $this->pagination->initialize($config);

        $data['stok_alat_kontrasepsi'] = $this->Stok_alat_kontrasepsi_model->get_all_stok_alat_kontrasepsi($params);
        
        $data['_view'] = 'stok_alat_kontrasepsi/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new alat_kontrasepsi
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('tipekb_id','Tipekb Id','required');
		$this->form_validation->set_rules('jml_stok','Jml Stok','numeric|required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'tipekb_id' => $this->input->post('tipekb_id'),
				'jml_stok' => $this->input->post('jml_stok'),
				'updated_at' => date('Y-m-d H:i:s'),
				'updated_by' => $this->session->userdata('admin_id'),
            );
            
            $alat_kontrasepsi_id = $this->Stok_alat_kontrasepsi_model->add_alat_kontrasepsi($params);
            redirect('stok_alat_kontrasepsi/index');
        }
        else
        {
			$this->load->model('Msttipekb_model');
			$data['all_msttipekb'] = $this->Msttipekb_model->get_all_msttipekb();
            
            $data['_view'] = 'stok_alat_kontrasepsi/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a alat_kontrasepsi
     */
    function edit($stok_id)
    {   
        // check if the alat_kontrasepsi exists before trying to edit it
        $data['alat_kontrasepsi'] = $this->Stok_alat_kontrasepsi_model->get_alat_kontrasepsi($stok_id);
        
        if(isset($data['alat_kontrasepsi']['stok_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('tipekb_id','Tipekb Id','required');
			$this->form_validation->set_rules('jml_stok','Jml Stok','numeric|required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'tipekb_id' => $this->input->post('tipekb_id'),
					'jml_stok' => $this->input->post('jml_stok'),
                'updated_at' => date('Y-m-d H:i:s'),
                'updated_by' => $this->session->userdata('admin_id'),
                );

                $this->Stok_alat_kontrasepsi_model->update_alat_kontrasepsi($stok_id,$params);            
                redirect('stok_alat_kontrasepsi/index');
            }
            else
            {
				$this->load->model('Msttipekb_model');
				$data['all_msttipekb'] = $this->Msttipekb_model->get_all_msttipekb();

                $data['_view'] = 'stok_alat_kontrasepsi/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The alat_kontrasepsi you are trying to edit does not exist.');
    } 

    /*
     * Deleting alat_kontrasepsi
     */
    function remove($stok_id)
    {
        $alat_kontrasepsi = $this->Stok_alat_kontrasepsi_model->get_alat_kontrasepsi($stok_id);

        // check if the alat_kontrasepsi exists before trying to delete it
        if(isset($alat_kontrasepsi['stok_id']))
        {
            $this->Stok_alat_kontrasepsi_model->delete_alat_kontrasepsi($stok_id);
            redirect('stok_alat_kontrasepsi/index');
        }
        else
            show_error('The alat_kontrasepsi you are trying to delete does not exist.');
    }
    
}
