<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class M_api extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user_aplikasi by user_id
     */
    function checkUserReg($field,$data)
    {
        $this->db->select('full_name')
        ->from('user_register')
        ->where('reg_status','1')
        ->where($field,$data);

        $query = $this->db->get();

        return $query->num_rows();
    }
    function checkUserRegVerify($field,$data)
    {
        $this->db->select('full_name')
        ->from('user_register')
        ->where($field,$data);

        $query = $this->db->get();

        return $query->num_rows();
    }

    function checkTokenLogin($where)
    {
        $this->db->select('full_name')
        ->from('mstuser')
        ->where($where);

        $query = $this->db->get();

        return $query->num_rows();
    }
     function checkUserActive($where,$tokenLogin = '')
    {
        if($tokenLogin != '')
        {
                $this->db->select('*')
                ->from('mstuser')
                ->where('active_status','1')
                ->where('token_login',$tokenLogin)
                ->where($where);
        }else
        {
            $this->db->select('*')
            ->from('mstuser')
            ->where('active_status','1')
            ->where($where);
        }

        $query = $this->db->get();

       

        return $query;
    }
    function insertData($data)
    {
        return $this->db->insert('user_register',$data);
    }
    function insert($table,$data)
    {
        return $this->db->insert($table,$data);
    }
    function updateData($table,$data,$where)
    {
       return $this->db->update($table, $data,$where);

    }

    function activateUser($nohp,$noktp,$pin)
    {
        $this->db->select('*')
        ->from('user_register')
        ->where('no_ktp',$noktp)
        ->where('no_hp',$nohp);

        $getData = $this->db->get()->row();

        $fullname = $getData->full_name;
        $email = $getData->email;
        $no_hp = $getData->no_hp;
        $no_ktp = $getData->no_ktp;
        $tgl_lahir = $getData->tgl_lahir;
        $kecamatan_id = $getData->kecamatan_id;
        $desa_id = $getData->desa_id;
        $alamat_detail = $getData->alamat_detail;

        $data = array(
            'full_name' => $fullname,
            'email' => $email,
            'no_hp' => $no_hp,
            'pin'   => $pin,
            'no_ktp' => $no_ktp,
            'active_status' => '1',
            'created_at' => date('Y-m-d H:i:s'),
            'tgl_lahir'     => date('Y-m-d',strtotime($tgl_lahir)),
            'kecamatan_id'  => $kecamatan_id,
            'desa_id'   => $desa_id,
            'alamat_detail' => $alamat_detail
        );
        $this->db->insert('mstuser',$data);

        $dataUpdate  = array('reg_status' => '1');
       return $this->db->update('user_register', $dataUpdate, array('no_ktp' => $noktp, 'no_hp' => $nohp));

    }
    
    function selectWhere($table,$where)
    {
        $this->db->select('*')
        ->from($table)
        ->where($where);

        $query = $this->db->get();

        return $query;
    }

    function selectWhereOrderDesc($table,$where)
    {
        $this->db->select('*')
        ->from($table)
        ->where($where)
        ->order_by('slider_id','desc');

        $query = $this->db->get();

        return $query;
    }

    function select($table)
    {
        $this->db->select('*')
        ->from($table);

        $query = $this->db->get();

        return $query;
    }

     function getDataJadwalPelayananTetap($table)
    {
       $query = $this->db->query("
            SELECT * from ".$table." a 
            join mstlokasipelayanan b on b.lokasipelayanan_id = a.lokasipelayanan_id
            join mstkecamatan c on c.kecamatan_id = b.kecamatan_id

        ");

        return $query;
    }

    function getDataJadwalPelayanan($table)
    {
       $query = $this->db->query("
            SELECT * from ".$table." a 
            join mstkecamatan b on b.kecamatan_id = a.kecamatan_id

        ");

        return $query;
    }


    function checkUserDaftarLayanan($user_id)
    {
       $query = $this->db->query("
            SELECT * from reg_pelayanan a
            join mstlokasipelayanan b on b.lokasipelayanan_id = a.lokasipelayanan_id
            join msttipekb c on c.tipekb_id = a.tipe_kb

            where a.user_id = ".$user_id."

        ");

        return $query;
    }

    

    function getDataRegisterLayananBaru()
    {
        $query = $this->db->query("
            SELECT c.nama_kecamatan,
            sum(case when a.tipe_kb = 1 then 1 else 0 end) as IUD,
            sum(case when a.tipe_kb = 2 then 1 else 0 end) as Suntik,
            sum(case when a.tipe_kb = 3 then 1 else 0 end) as Implan,
            sum(case when a.tipe_kb = 4 then 1 else 0 end) as Pil,
            sum(case when a.tipe_kb = 5 then 1 else 0 end) as Kondom,
            sum(case when a.tipe_kb = 6 then 1 else 0 end) as MOP,
            sum(case when a.tipe_kb = 7 then 1 else 0 end) as MOW

                        from reg_pelayanan a 
                            join mstlokasipelayanan b on b.lokasipelayanan_id = a.lokasipelayanan_id
                            join mstkecamatan c on c.kecamatan_id = b.kecamatan_id
                            join msttipekb d on d.tipekb_id = a.tipe_kb
                            where a.user_id not in (select user_id from user_history_pelayanan)
                         GROUP by c.nama_kecamatan order by c.nama_kecamatan asc
                
            ");

        return $query;
    }

     function getDataRegisterLayananAktif()
    {
        $query = $this->db->query("
            SELECT c.nama_kecamatan,
            sum(case when a.tipe_kb = 1 then 1 else 0 end) as IUD,
            sum(case when a.tipe_kb = 2 then 1 else 0 end) as Suntik,
            sum(case when a.tipe_kb = 3 then 1 else 0 end) as Implan,
            sum(case when a.tipe_kb = 4 then 1 else 0 end) as Pil,
            sum(case when a.tipe_kb = 5 then 1 else 0 end) as Kondom,
            sum(case when a.tipe_kb = 6 then 1 else 0 end) as MOP,
            sum(case when a.tipe_kb = 7 then 1 else 0 end) as MOW

                        from reg_pelayanan a 
                            join mstlokasipelayanan b on b.lokasipelayanan_id = a.lokasipelayanan_id
                            join mstkecamatan c on c.kecamatan_id = b.kecamatan_id
                            join msttipekb d on d.tipekb_id = a.tipe_kb
                            where a.user_id in (select user_id from user_history_pelayanan)
                         GROUP by c.nama_kecamatan order by c.nama_kecamatan asc
                
            ");

        return $query;
    }

    function stokAlatKontrasepsi()
    {
        return $this->db->query("
            SELECT * from stok_alat_kontrasepsi a
            join msttipekb b on b.tipekb_id = a.tipekb_id
            ");
    }

    function getDataUser($user_id)
    {
        return $this->db->query("
            SELECT * from mstuser a
            join mstkecamatan b on b.kecamatan_id = a.kecamatan_id
            join mstdesa c on c.desa_id = a.desa_id
            where user_id = '".$user_id."'
            ");
    }

     function getDataLokasi2()
    {
       $query = $this->db->query("
            SELECT * from mstlokasipelayanan a 
            join mstkecamatan b on b.kecamatan_id = a.kecamatan_id

        ");

        return $query;
    }

    

     function getDataLokasi($kecamatan,$jeniskb)
    {
       $query = $this->db->query("
            SELECT nama_lokasi,a.lokasipelayanan_id,d.nama_kecamatan FROM `lokasidanjeniskb` a 
                inner join mstlokasipelayanan b on b.lokasipelayanan_id = a.lokasipelayanan_id
                inner join msttipekb c on c.tipekb_id = a.tipekb_id
                inner join mstkecamatan d on d.kecamatan_id = b.kecamatan_id
                where d.nama_kecamatan = '".$kecamatan."' and c.nama_tipe = '".$jeniskb."'

        ");

        return $query;
    }
    
}
