<?php
/* b
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class M_dataperiode extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get dataperiode by dataperiode_id
     */
    function get_dataperiode($idperiode)
    {
        $dataperiode = $this->db->query("
            SELECT
                *

            FROM
                `mstperiode`

            WHERE
                `idperiode` = ?
        ",array($idperiode))->row_array();

        return $dataperiode;
    }
    
    /*
     * Get all mstdataperiode count
     */
    function get_all_dataperiode_count()
    {
        $mstdataperiode = $this->db->query("
            SELECT
                count(*) as count

            FROM
                `mstperiode`
        ")->row_array();

        return $mstdataperiode['count'];
    }
        
    /*
     * Get all mstdataperiode
     */
    function get_all_dataperiode($params = array())
    {
        $limit_condition = "";
        if(isset($params) && !empty($params))
            $limit_condition = " LIMIT " . $params['offset'] . "," . $params['limit'];
        
        $mstdataperiode = $this->db->query("
            SELECT
                *

            FROM
                `mstperiode` a 

            WHERE
                1 = 1

            ORDER BY `idperiode` DESC
        ")->result_array();

        return $mstdataperiode;
    }
        
    /*
     * function to add new dataperiode
     */
    function add_dataperiode($params)
    {
        $this->db->insert('mstperiode',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update dataperiode
     */
    function update_dataperiode($dataperiode_id,$params)
    {
        $this->db->where('idperiode',$dataperiode_id);
        return $this->db->update('mstperiode',$params);
    }
    
    /*
     * function to delete dataperiode
     */
    function delete_dataperiode($dataperiode_id)
    {
        return $this->db->delete('mstperiode',array('idperiode'=>$dataperiode_id));
    }
}
