 <?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class M_imageslider extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get image_banner by slider_id
     */
    function get_image_banner($slider_id)
    {
        $image_banner = $this->db->query("
            SELECT
                *

            FROM
                `image_slider`

            WHERE
                `slider_id` = ?
        ",array($slider_id))->row_array();

        return $image_banner;
    }
    
    /*
     * Get all image_slider count
     */
    function get_all_image_slider_count()
    {
        $image_slider = $this->db->query("
            SELECT
                count(*) as count

            FROM
                `image_slider`
        ")->row_array();

        return $image_slider['count'];
    }
        
    /*
     * Get all image_slider
     */
    function get_all_image_slider($params = array())
    {
        $limit_condition = "";
        if(isset($params) && !empty($params))
            $limit_condition = " LIMIT " . $params['offset'] . "," . $params['limit'];
        
        $image_slider = $this->db->query("
            SELECT
                a.*,b.full_name

            FROM
                `image_slider` a 
                JOIN mstadmin b on b.admin_id = a.created_by

            WHERE
                1 = 1

            ORDER BY `slider_id` DESC

            
        ")->result_array();

        return $image_slider;
    }
        
    /*
     * function to add new image_banner
     */
    function add_image_banner($params)
    {
        $this->db->insert('image_slider',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update image_banner
     */
    function update_image_banner($slider_id,$params)
    {
        $this->db->where('slider_id',$slider_id);
        return $this->db->update('image_slider',$params);
    }
    
    /*
     * function to delete image_banner
     */
    function delete_image_banner($slider_id)
    {
        return $this->db->delete('image_slider',array('slider_id'=>$slider_id));
    }
}
