<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class M_jadwalpelayananterpusat extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get info_jadwal_pelayanan_tetap by jadwal_id
     */
    function get_info_jadwal_pelayanan_tetap($jadwal_id)
    {
        $info_jadwal_pelayanan_tetap = $this->db->query("
            SELECT
                *

            FROM
                `info_jadwalpelayananterpusat`

            WHERE
                `jadwal_id` = ?
        ",array($jadwal_id))->row_array();

        return $info_jadwal_pelayanan_tetap;
    }
    
    /*
     * Get all info_jadwalpelayanantetap count
     */
    function get_all_info_jadwalpelayananterpusat_count()
    {
        $info_jadwalpelayanantetap = $this->db->query("
            SELECT
                count(*) as count

            FROM
                `info_jadwalpelayananterpusat`
        ")->row_array();

        return $info_jadwalpelayanantetap['count'];
    }
        
    /*
     * Get all info_jadwalpelayanantetap
     */
    function get_all_info_jadwalpelayananterpusat($params = array())
    {
        $limit_condition = "";
        if(isset($params) && !empty($params))
            $limit_condition = " LIMIT " . $params['offset'] . "," . $params['limit'];
        
        $info_jadwalpelayanantetap = $this->db->query("
            SELECT
                *

            FROM
                `info_jadwalpelayananterpusat` a 
                join mstkecamatan b on b.kecamatan_id = a.kecamatan_id

            WHERE
                1 = 1

            ORDER BY `jadwal_id` DESC

        ")->result_array();

        return $info_jadwalpelayanantetap;
    }
        
    /*
     * function to add new info_jadwal_pelayanan_tetap
     */
    function add_info_jadwal_pelayanan_tetap($params)
    {
        $this->db->insert('info_jadwalpelayananterpusat',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update info_jadwal_pelayanan_tetap
     */
    function update_info_jadwal_pelayanan_tetap($jadwal_id,$params)
    {
        $this->db->where('jadwal_id',$jadwal_id);
        return $this->db->update('info_jadwalpelayananterpusat',$params);
    }
    
    /*
     * function to delete info_jadwal_pelayanan_tetap
     */
    function delete_info_jadwal_pelayanan_tetap($jadwal_id)
    {
        return $this->db->delete('info_jadwalpelayananterpusat',array('jadwal_id'=>$jadwal_id));
    }
}
