<?php
/* b
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Mstdesa_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get desa by desa_id
     */
    function get_desa($desa_id)
    {
        $desa = $this->db->query("
            SELECT
                *

            FROM
                `mstdesa`

            WHERE
                `desa_id` = ?
        ",array($desa_id))->row_array();

        return $desa;
    }
    
    /*
     * Get all mstdesa count
     */
    function get_all_mstdesa_count()
    {
        $mstdesa = $this->db->query("
            SELECT
                count(*) as count

            FROM
                `mstdesa`
        ")->row_array();

        return $mstdesa['count'];
    }
        
    /*
     * Get all mstdesa
     */
    function get_all_mstdesa($params = array())
    {
        $limit_condition = "";
        if(isset($params) && !empty($params))
            $limit_condition = " LIMIT " . $params['offset'] . "," . $params['limit'];
        
        $mstdesa = $this->db->query("
            SELECT
                *

            FROM
                `mstdesa` a 
                join mstkecamatan b on b.kecamatan_id = a.kecamatan_id

            WHERE
                1 = 1

            ORDER BY `desa_id` DESC

        ")->result_array();

        return $mstdesa;
    }
        
    /*
     * function to add new desa
     */
    function add_desa($params)
    {
        $this->db->insert('mstdesa',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update desa
     */
    function update_desa($desa_id,$params)
    {
        $this->db->where('desa_id',$desa_id);
        return $this->db->update('mstdesa',$params);
    }
    
    /*
     * function to delete desa
     */
    function delete_desa($desa_id)
    {
        return $this->db->delete('mstdesa',array('desa_id'=>$desa_id));
    }
}
