<?php 
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Mstunit_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get unit by unit_id
     */
    function get_unit($unit_id)
    {
        $unit = $this->db->query("
            SELECT
                *

            FROM
                `mstunit`

            WHERE
                `unit_id` = ?
        ",array($unit_id))->row_array();

        return $unit;
    }
    
    /*
     * Get all mstunit count
     */
    function get_all_mstunit_count()
    {
        $mstunit = $this->db->query("
            SELECT
                count(*) as count

            FROM
                `mstunit`
        ")->row_array();

        return $mstunit['count'];
    }
        
    /*
     * Get all mstunit
     */
    function get_all_mstunit($params = array())
    {
        $limit_condition = "";
        if(isset($params) && !empty($params))
            $limit_condition = " LIMIT " . $params['offset'] . "," . $params['limit'];
        
        $mstunit = $this->db->query("
            SELECT
                *

            FROM
                `mstunit`

            WHERE
                1 = 1

            ORDER BY `unit_id` DESC

        ")->result_array();

        return $mstunit;
    }
        
    /*
     * function to add new unit
     */
    function add_unit($params)
    {
        $this->db->insert('mstunit',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update unit
     */
    function update_unit($unit_id,$params)
    {
        $this->db->where('unit_id',$unit_id);
        return $this->db->update('mstunit',$params);
    }
    
    /*
     * function to delete unit
     */
    function delete_unit($unit_id)
    {
        return $this->db->delete('mstunit',array('unit_id'=>$unit_id));
    }
}
