 <?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class M_indikator extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get image_banner by slider_id
     */
    function get_indikator($id_laporan)
    {
        $image_banner = $this->db->query("
            SELECT
                *

            FROM
                `mstlaporan`

            WHERE
                `id_laporan` = ?
        ",array($id_laporan))->row_array();

        return $image_banner;
    }
   
    /*
     * Get all image_slider
     */
    function get_all_indikator_bulanan()
    {
       
        $image_slider = $this->db->query("
            SELECT
               *

            FROM
                `mstlaporan` 

            WHERE
                tipe = 'bulanan'

            ORDER BY `tahun` DESC

            
        ")->result_array();

        return $image_slider;
    }

    function get_all_indikator_tahunan()
    {
       
        $image_slider = $this->db->query("
            SELECT
               *

            FROM
                `mstlaporan` 

            WHERE
                tipe = 'tahunan'

            ORDER BY `id_laporan` DESC

            
        ")->result_array();

        return $image_slider;
    }
        
    /*
     * function to add new image_banner
     */
    function add_indikator($params)
    {
        $this->db->insert('mstlaporan',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update image_banner
     */
    function update_indikator($id_laporan,$params)
    {
        $this->db->where('id_laporan',$id_laporan);
        return $this->db->update('mstlaporan',$params);
    }
    
    /*
     * function to delete image_banner
     */
    function delete_indikator($id_laporan)
    {
        return $this->db->delete('mstlaporan',array('id_laporan'=>$id_laporan));
    }
}
