<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class M_userapps extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user_aplikasi by user_id
     */
    function get_user_aplikasi($user_id)
    {
        $user_aplikasi = $this->db->query("
            SELECT
                *

            FROM
                `mstuser`

            WHERE
                `user_id` = ?
        ",array($user_id))->row_array();

        return $user_aplikasi;
    }
    
    /*
     * Get all mstunit count
     */
    function get_all_mstunit_count()
    {
        $mstunit = $this->db->query("
            SELECT
                count(*) as count

            FROM
                `mstuser` 
        ")->row_array();

        return $mstunit['count'];
    }
        
    /*
     * Get all mstunit
     */
    function get_all_mstunit($params = array())
    {
        $limit_condition = "";
        if(isset($params) && !empty($params))
            $limit_condition = " LIMIT " . $params['offset'] . "," . $params['limit'];
        
        $mstunit = $this->db->query("
            SELECT
                *

            FROM
                `mstuser`a 
                join mstkecamatan b on b.kecamatan_id = a.kecamatan_id
                join mstdesa c on c.desa_id = a.desa_id

            WHERE
                1 = 1

            ORDER BY `user_id` DESC

        ")->result_array();

        return $mstunit;
    }
        
    /*
     * function to add new user_aplikasi
     */
    function add_user_aplikasi($params)
    {
        $this->db->insert('mstuser',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update user_aplikasi
     */
    function update_user_aplikasi($user_id,$params)
    {
        $this->db->where('user_id',$user_id);
        return $this->db->update('mstuser',$params);
    }
    
    /*
     * function to delete user_aplikasi
     */
    function delete_user_aplikasi($user_id)
    {
        return $this->db->delete('mstuser',array('user_id'=>$user_id));
    }
}
