<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Mstmenu_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get menu by menu_id
     */
    function get_menu($menu_id)
    {
        $menu = $this->db->query("
            SELECT
                *
            FROM
                `mstmenu`
            WHERE
                `menu_id` = ?
        ",array($menu_id))->row_array();

        return $menu;
    }
        
    /*
     * Get all mstmenu
     */
    function get_all_mstmenu()
    {
        $mstmenu = $this->db->query("
            SELECT  a.*, b.menu_name AS parent_menu_name FROM  `mstmenu` a
LEFT JOIN mstmenu b ON b.menu_id = a.parent_menu

        ")->result_array();

        return $mstmenu;
    }
        
    /*
     * function to add new menu
     */
    function add_menu($params)
    {
        $this->db->insert('mstmenu',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update menu
     */
    function update_menu($menu_id,$params)
    {
        $this->db->where('menu_id',$menu_id);
        return $this->db->update('mstmenu',$params);
    }
    
    /*
     * function to delete menu
     */
    function delete_menu($menu_id)
    {
        return $this->db->delete('mstmenu',array('menu_id'=>$menu_id));
    }
}
