<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Stok_alat_kontrasepsi_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get alat_kontrasepsi by stok_id
     */
    function get_alat_kontrasepsi($stok_id)
    {
        $alat_kontrasepsi = $this->db->query("
            SELECT
                *

            FROM
                `stok_alat_kontrasepsi`

            WHERE
                `stok_id` = ?
        ",array($stok_id))->row_array();

        return $alat_kontrasepsi;
    }
    
    /*
     * Get all stok_alat_kontrasepsi count
     */
    function get_all_stok_alat_kontrasepsi_count()
    {
        $stok_alat_kontrasepsi = $this->db->query("
            SELECT
                count(*) as count

            FROM
                `stok_alat_kontrasepsi`
        ")->row_array();

        return $stok_alat_kontrasepsi['count'];
    }
        
    /*
     * Get all stok_alat_kontrasepsi
     */
    function get_all_stok_alat_kontrasepsi($params = array())
    {
        $limit_condition = "";
        if(isset($params) && !empty($params))
            $limit_condition = " LIMIT " . $params['offset'] . "," . $params['limit'];
        
        $stok_alat_kontrasepsi = $this->db->query("
            SELECT
                *

            FROM
                `stok_alat_kontrasepsi`

            WHERE
                1 = 1

            ORDER BY `stok_id` DESC

        ")->result_array();

        return $stok_alat_kontrasepsi;
    }
        
    /*
     * function to add new alat_kontrasepsi
     */
    function add_alat_kontrasepsi($params)
    {
        $this->db->insert('stok_alat_kontrasepsi',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update alat_kontrasepsi
     */
    function update_alat_kontrasepsi($stok_id,$params)
    {
        $this->db->where('stok_id',$stok_id);
        return $this->db->update('stok_alat_kontrasepsi',$params);
    }
    
    /*
     * function to delete alat_kontrasepsi
     */
    function delete_alat_kontrasepsi($stok_id)
    {
        return $this->db->delete('stok_alat_kontrasepsi',array('stok_id'=>$stok_id));
    }
}
