<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Useradmin_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get admin by admin_id
     */
    function get_admin($admin_id)
    {
        $admin = $this->db->query("
            SELECT
                *

            FROM
                `mstadmin`

            WHERE
                `admin_id` = ?
        ",array($admin_id))->row_array();

        return $admin;
    }
    
    /*
     * Get all mstadmin count
     */
    function get_all_mstadmin_count()
    {
        $mstadmin = $this->db->query("
            SELECT
                count(*) as count

            FROM
                `mstadmin`
        ")->row_array();

        return $mstadmin['count'];
    }
        
    /*
     * Get all mstadmin
     */
    function get_all_mstadmin()
    {
       
        
        $mstadmin = $this->db->query("
            SELECT
                *
            FROM
                `mstadmin` a
                join mstlevel_akses c on c.level_id = a.level_akses
                left join mstlokasipelayanan d on d.lokasipelayanan_id = a.lokasipelayanan_id

            WHERE
                1 = 1

            ORDER BY `admin_id` DESC

        ")->result_array();

        return $mstadmin;
    }
        
    /*
     * function to add new admin
     */
    function add_admin($params)
    {
        $this->db->insert('mstadmin',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update admin
     */
    function update_admin($admin_id,$params)
    {
        $this->db->where('admin_id',$admin_id);
        return $this->db->update('mstadmin',$params);
    }
    
    /*
     * function to delete admin
     */
    function delete_admin($admin_id)
    {
        return $this->db->delete('mstadmin',array('admin_id'=>$admin_id));
    }

    public function checkUser($email, $password) {
        
        $this->db->select('*');
        $this->db->from('mstadmin');
        $this->db->where('email', $email);
        $this->db->where('password', $password);
        $this->db->where('active_status', 1);
        $this->db->limit(1);
        
        $query = $this->db->get();
        
        if($query->num_rows() == 1) {
            return $query->result();
        }
        else {
            return false;
        }
    }

    function getUserMenu($level_id)
    {
       return $this->db->query("SELECT a.menu_id,a.level_id,b.menu_name,b.parent_menu,b.script_menu,b.menu_fas from usermenu a 
                    join mstmenu b on b.menu_id = a.menu_id where level_id =  ".$level_id." 
                    ORDER BY menu_name ASC, parent_menu asc");
    }
}
