<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Usermenu_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user_menu by idusermenu
     */
    function get_user_menu($idusermenu)
    {
        $user_menu = $this->db->query("
            SELECT
                *

            FROM
                `usermenu`

            WHERE
                `idusermenu` = ?
        ",array($idusermenu))->row_array();

        return $user_menu;
    }
    
    /*
     * Get all usermenu count
     */
    function get_all_usermenu_count()
    {
        $usermenu = $this->db->query("
            SELECT
                count(*) as count

            FROM
                `usermenu`
        ")->row_array();

        return $usermenu['count'];
    }
        
    /*
     * Get all usermenu
     */
    function get_all_usermenu($params = array())
    {
        $limit_condition = "";
        if(isset($params) && !empty($params))
            $limit_condition = " LIMIT " . $params['offset'] . "," . $params['limit'];
        
        $usermenu = $this->db->query("
            SELECT
                *

            FROM
                `usermenu`

            WHERE
                1 = 1

            ORDER BY `idusermenu` DESC

        ")->result_array();

        return $usermenu;
    }

    function getmenu()
    {
         $limit_condition = "";
        if(isset($params) && !empty($params))
            $limit_condition = " LIMIT " . $params['offset'] . "," . $params['limit'];

        return $this->db->query("SELECT * from usermenu a 
                    join mstmenu b on b.menu_id = a.menu_id 
                    JOIN mstlevel_akses c ON c.level_id = a.level_id ". $limit_condition . "")->result_array();
    }
        
    /*
     * function to add new user_menu
     */
    function add_user_menu($params)
    {
        $this->db->insert('usermenu',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update user_menu
     */
    function update_user_menu($idusermenu,$params)
    {
        $this->db->where('idusermenu',$idusermenu);
        return $this->db->update('usermenu',$params);
    }
    
    /*
     * function to delete user_menu
     */
    function delete_user_menu($idusermenu)
    {
        return $this->db->delete('usermenu',array('idusermenu'=>$idusermenu));
    }
}
