<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class ApiHome extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('m_api','model');
        if(count($this->input->post()) < 1)
        {
            $json = array('status'=>404, 'message'=>"no request data");
            echo json_encode($json);
            die;
        }
        
    }

    function index()
    {
        echo "on";
    }

    function getImageSlider()
    {
    
        $tokenLogin          = secure_input($this->input->post('tokenLogin'));

        $checkToken = $this->model->checkTokenLogin(array('token_login'=> $tokenLogin));

        if($checkToken < 1)
        {
            $json = array('status'=>201, 'message'=>"invalid token");
            echo json_encode($json);
            die;
        }

        $dataImage = array();

        $getImage = $this->model->selectWhereOrderDesc('image_slider',array('active_status' => '1'));
        $datenow = strtotime(date('Y-m-d H:i:s'));

        if($getImage->num_rows() > 0)
        {
            foreach ($getImage->result() as $key) {
                $startdate = strtotime($key->start_date);
                $enddate = strtotime($key->end_date);

                if($startdate <= $datenow && $enddate >= $datenow)
                {
                    $d['image_url'] = $key->slider_url;
                    array_push($dataImage, $d);
                }
            }
        }


            
            $json = array('status'=>200, 'message'=>"success","image_url" => $dataImage);

        
     
        echo json_encode($json);
        
    }

    function getArtikel()
    {
        $tokenLogin          = secure_input($this->input->post('tokenLogin'));

        $checkToken = $this->model->checkTokenLogin(array('token_login'=> $tokenLogin));

        if($checkToken < 1)
        {
            $json = array('status'=>201, 'message'=>"invalid token");
            echo json_encode($json);
            die;
        }

        $dataArtikel = array();

        $getArtikel = $this->model->selectWhere('mstinfo',array('active_status' => '1'));
       

        if($getArtikel->num_rows() > 0)
        {
            foreach ($getArtikel->result() as $key) {
                
                    $d['info_id']     = $key->info_id;
                    $d['image_url']     = $key->image_url;
                    $d['info_title']    = $key->info_title;
                    $d['info_summary']   = $key->info_summary."..";
                    $d['info_desc']     = $key->info_desc;
                    $d['created_at']    = date('d-m-Y H:i',strtotime($key->created_at));
                    array_push($dataArtikel, $d);
                
            }
        }


            
            $json = array('status'=>200, 'message'=>"success","artikel" => $dataArtikel);

        
     
        echo json_encode($json);
    }

     function getArtikelDetail()
    {
        $tokenLogin          = secure_input($this->input->post('tokenLogin'));
        $info_id          = secure_input($this->input->post('info_id'));

        $checkToken = $this->model->checkTokenLogin(array('token_login'=> $tokenLogin));

        if($checkToken < 1)
        {
            $json = array('status'=>201, 'message'=>"invalid token");
            echo json_encode($json);
            die;
        }

        $dataArtikel = array();

        $getArtikel = $this->model->selectWhere('mstinfo',array('info_id' => $info_id));
       

        if($getArtikel->num_rows() > 0)
        {
            foreach ($getArtikel->result() as $key) {
                
                    $d['info_id']     = $key->info_id;
                    $d['image_url']     = $key->image_url;
                    $d['info_title']    = $key->info_title;
                    $d['info_summary']   = $key->info_summary."..";
                    $d['info_desc']     = $key->info_desc;
                    $d['created_at']    = date('d-m-Y H:i',strtotime($key->created_at));
                    array_push($dataArtikel, $d);
                
            }
        }


            
            $json = array('status'=>200, 'message'=>"success","artikel" => $dataArtikel);

        
     
        echo json_encode($json);
    }

     function getDataUser()
    {
        $user_id          = secure_input($this->input->post('user_id'));
        $tokenLogin     = secure_input($this->input->post('tokenLogin'));

     
        $checkNoKtp = $this->model->checkUserActive(array('user_id'=>$user_id),$tokenLogin);

        if($checkNoKtp->num_rows() < 1)
        {
            $json = array('status'=>201, 'message'=>"data anda tidak terdaftar / akun tidak aktif");

        }else 
        {
            $dataUser = $this->model->getDataUser($user_id);
            $data       = $dataUser->row();
            $userId     = $data->user_id;
            $fullName   = $data->full_name;
            $noHp        = $data->no_hp;
            $email      = $data->email;
            $noKtp      = $data->no_ktp;
            $tokenLogin   = $data->token_login;
            $link_image   = $data->link_image;

            $kelurahan      = $data->nama_desa;
            $kecamatan          = $data->nama_kecamatan;
            $alamat_detail   = $data->alamat_detail;
            $tanggal_lahir   = $this->tanggalIndo(date('d-m-Y',strtotime($data->tgl_lahir)));


            $linkImage = "";
            if($link_image != "")
            {
                $linkImage = base_url()."upload/fotoakun/".$link_image;
            }

            $json = array(
                'status'=>200, 
                'message'=>"berhasil",
                'full_name' => $fullName,
                'no_ktp' => $noKtp,
                'no_hp' => $noHp,
                'email' => $email,
                'file_image' => $linkImage,
                'kelurahan' => $kelurahan,
                'kecamatan' => $kecamatan,
                'alamat_detail' => $alamat_detail,
                'tanggal_lahir' => $tanggal_lahir

            );

        } 
     
        echo json_encode($json);
    }

     function updateUser()
    {
        $user_id       = secure_input($this->input->post('user_id'));
        $tokenLogin    = secure_input($this->input->post('tokenLogin'));
        $noKtp         = secure_input($this->input->post('noKtp'));
        $noHp          = secure_input($this->input->post('noHp'));
        $email         = secure_input($this->input->post('email'));
        $fullName      = secure_input($this->input->post('fullName'));
        $file          = secure_input($this->input->post('file'));


        // $log = date("d-m-Y H:i:s").PHP_EOL.
        // print_r($_POST, true).PHP_EOL; 
        // file_put_contents('test.txt',$log);

     
        $checkNoKtp = $this->model->checkUserActive(array('user_id'=>$user_id),$tokenLogin);

        if($checkNoKtp->num_rows() < 1)
        {
            $json = array('status'=>201, 'message'=>"data anda tidak terdaftar / akun tidak aktif");

        }else 
        {
            if(trim($file) != "")
            {
                $new_namePP = "";
                $new_namePP ="IMG_AKUN_".$user_id.date('YmdHis');
    
                $UPLOAD_DIR = "upload/fotoakun/";
                    
                $image_base64 = base64_decode($file);
                $filename = $UPLOAD_DIR . $new_namePP.'.png';
                file_put_contents($filename, $image_base64);

                $new_namePP=$new_namePP.'.png';


                $dataUpdate = array(
                    'full_name' => $fullName,
                    'no_hp' => $noHp,
                    'no_ktp' => $noKtp,
                    'email' => $email,
                    'link_image'=> $new_namePP
                );

            }else
            {
                 $dataUpdate = array(
                    'full_name' => $fullName,
                    'no_hp' => $noHp,
                    'no_ktp' => $noKtp,
                    'email' => $email
                );

            }
                $data = $this->model->updateData('mstuser', $dataUpdate, array('user_id' => $user_id));

            $json = array(
                'status'=>200, 
                'message'=>"berhasil",
                'full_name' => $fullName,
                'no_ktp' => $noKtp,
                'no_hp' => $noHp,
                'email' => $email,
                'tokenLogin'    => $tokenLogin

            );

        } 
     
        echo json_encode($json);
    }

    function listJadwalTetap()
    {
        $user_id          = secure_input($this->input->post('user_id'));
        $tokenLogin     = secure_input($this->input->post('tokenLogin'));

     
        $checkNoKtp = $this->model->checkUserActive(array('user_id'=>$user_id),$tokenLogin);
        $json = array('status'=>201, 'message'=>"data anda tidak terdaftar / akun tidak aktif");
       if($checkNoKtp->num_rows() < 1)
        {
            $json = array('status'=>201, 'message'=>"data anda tidak terdaftar / akun tidak aktif");

        }else 
        {
            $data = array();

            $getData = $this->model->getDataJadwalPelayananTetap("info_jadwalpelayanantetap");
           

            if($getData->num_rows() > 0)
            {
                foreach ($getData->result() as $key) {

                    
                        $d['id']     = $key->info_jadwal_id;
                        $d['nama_kecamatan']     = $key->nama_kecamatan;
                        $d['nama_lokasi']     = $key->nama_kecamatan." - ".$key->nama_lokasi;
                        $d['tanggal']    = $key->tanggal;
                        $d['jam_mulai']   = date('H:i',strtotime($key->jam_mulai));
                        $d['jam_akhir']     = date('H:i',strtotime($key->jam_selesai));
                        $d['keterangan']    = $key->keterangan;
                        array_push($data, $d);
                    
                }
            }
            $json = array('status'=>200, 'message'=>"success","data" => $data);

        } 
     
        echo json_encode($json);
    }

    

     function listJadwalTerpusat()
    {
        $user_id          = secure_input($this->input->post('user_id'));
        $tokenLogin     = secure_input($this->input->post('tokenLogin'));

     
        $checkNoKtp = $this->model->checkUserActive(array('user_id'=>$user_id),$tokenLogin);

       if($checkNoKtp->num_rows() < 1)
        {
            $json = array('status'=>201, 'message'=>"data anda tidak terdaftar / akun tidak aktif");

        }else 
        {
            $data = array();

            $getData = $this->model->getDataJadwalPelayanan("info_jadwalpelayananterpusat");
           

            if($getData->num_rows() > 0)
            {
                foreach ($getData->result() as $key) {

                    $tanggal = $this->tanggalIndo(date('d-m-Y',strtotime($key->tanggal)));
                    
                        $d['id']            = $key->jadwal_id;
                        $d['nama_lokasi']    = $key->nama_kecamatan." - ".$key->tempat_pelayanan;
                        $d['tanggal']       = $tanggal;
                        $d['jam_mulai']   = date('H:i',strtotime($key->jam_mulai));
                        $d['jam_akhir']     = date('H:i',strtotime($key->jam_selesai));
                        $d['keterangan']    = $key->keterangan;
                        array_push($data, $d);
                    
                }
            }
            $json = array('status'=>200, 'message'=>"success","data" => $data);

        } 
     
        echo json_encode($json);
    }

    function tanggalIndo($date)
    {
        $expl = explode('-', $date);
        $tgl = $expl[0];
        $bulan = $expl[1];
        $tahun = $expl[2];

        switch ($bulan) {
            case '1': $bulan = "Januari"; break;
            case '2': $bulan = "Februari"; break;
            case '3': $bulan = "Maret"; break;
            case '4': $bulan = "April"; break;
            case '5': $bulan = "Mei"; break;
            case '6': $bulan = "Juni"; break;
            case '7': $bulan = "Juli"; break;
            case '8': $bulan = "Agustus"; break;
            case '9': $bulan = "September"; break;
            case '10': $bulan = "oktober"; break;
            case '11': $bulan = "November"; break;
            case '12': $bulan = "Desember"; break;
        }

        return $tahun." ".$bulan." ".$tgl;
    }

    function getInitialDataDaftar()
    {
        $user_id          = secure_input($this->input->post('user_id'));
        $tokenLogin     = secure_input($this->input->post('tokenLogin'));

     
        $checkNoKtp = $this->model->checkUserActive(array('user_id'=>$user_id),$tokenLogin);

       if($checkNoKtp->num_rows() < 1)
        {
            $json = array('status'=>201, 'message'=>"data anda tidak terdaftar / akun tidak aktif");

        }else 
        {


            $dataJenis = array();
            $dataLokasi = array();
            $dataJaminanKesehatan = array();
            $dataKecamatan = array();

            $nama = "";$noKtp = "";$noHp = "";$email = "";$alamat = "";
            $noBpjs = "";$ivaTest = "";$jeniskb = "";$lokasilayanan = "";

            $getDataJenis = $this->model->select('msttipekb');
            $getDataLokasi = $this->model->getDataLokasi2();


            $getDataJenis = $this->model->select('msttipekb');
            $getDataKecamatan = $this->model->select('mstkecamatan');

            $checkUdahDaftar = $this->model->checkUserDaftarLayanan($user_id);
            if($checkUdahDaftar->num_rows() > 0)
            {
                $dataReg    = $checkUdahDaftar->row();
                $nama       = $dataReg->nama_lengkap;
                $noKtp      = $dataReg->no_ktp;
                $noHp       = $dataReg->no_telp;
                $email      = $dataReg->email;
                $alamat     = $dataReg->alamat;
                $noBpjs     = $dataReg->no_bpjs;
                $ivaTest    = $dataReg->iva_test;
                $jeniskb    = $dataReg->nama_tipe;
                $lokasilayanan = $dataReg->nama_lokasi;
                
            }
           

            if($getDataJenis->num_rows() > 0)
            {
                foreach ($getDataJenis->result() as $key) {
                    
                        $d['jenis_id']     = $key->tipekb_id;
                        $d['nama_jenis']     = $key->nama_tipe;
                        array_push($dataJenis, $d);
                    
                }
            }

             if($getDataKecamatan->num_rows() > 0)
            {
                foreach ($getDataKecamatan->result() as $key) {
                    
                        $daa['kecamatan_id']     = $key->kecamatan_id;
                        $daa['nama_kecamatan']     = $key->nama_kecamatan;
                        array_push($dataKecamatan, $daa);
                    
                }
            }

             if($getDataLokasi->num_rows() > 0)
            {
                foreach ($getDataLokasi->result() as $key) {

                    
                        $da['lokasi_id']     = $key->lokasipelayanan_id;
                        $da['nama_lokasi']     = $key->nama_lokasi;
                        $da['nama_kecamatan']     = $key->nama_kecamatan;
                        array_push($dataLokasi, $da);
                    
                }
            }

                        $da1['jenis_id']     = "1";
                        $da1['nama_jenis']     = "BPJS";
                        array_push($dataJaminanKesehatan, $da1);

                        $da2['jenis_id']     = "2";
                        $da2['nama_jenis']     = "Non-BPJS";
                        array_push($dataJaminanKesehatan, $da2);

                        $da3['jenis_id']     = "3";
                        $da3['nama_jenis']     = "UHJ";
                        array_push($dataJaminanKesehatan, $da3);

            $json = array('status'=>200, 
                'message'=>"success",
                "dataLokasi" => $dataLokasi,
                "dataJenisKB" => $dataJenis,
                "dataKecamatan" => $dataKecamatan,
                "dataJaminanKesehatan" => $dataJaminanKesehatan,
                "nama" => $nama,
                "noKtp" => $noKtp,
                "noHp" => $noHp,
                "email" => $email,
                "alamat" => $alamat,
                "noBpjs" => $noBpjs,
                "ivaTest" => $ivaTest,
                "jeniskb" => $jeniskb,
                "lokasilayanan" => $lokasilayanan,
            );

        } 
     
        echo json_encode($json);
    }

    function listLokasiKb()
    {

        $user_id        = secure_input($this->input->post('user_id'));
        $tokenLogin     = secure_input($this->input->post('tokenLogin'));
        $kecamatan      = secure_input($this->input->post('kecamatan'));
        $jenisKb        = secure_input($this->input->post('jenisKb'));

     
        $checkNoKtp = $this->model->checkUserActive(array('user_id'=>$user_id),$tokenLogin);

       if($checkNoKtp->num_rows() < 1)
        {
            $json = array('status'=>201, 'message'=>"data anda tidak terdaftar / akun tidak aktif");

        }else 
        {

            $dataLokasi = array();
            $getDataLokasi = $this->model->getDataLokasi($kecamatan,$jenisKb);


             if($getDataLokasi->num_rows() > 0)
            {
                foreach ($getDataLokasi->result() as $key) {

                    
                        $da['lokasi_id']        = $key->lokasipelayanan_id;
                        $da['nama_lokasi']     = $key->nama_lokasi;
                        $da['nama_kecamatan']  = $key->nama_kecamatan;
                        array_push($dataLokasi, $da);
                    
                }
            }

                       

            $json = array('status'=>200, 
                'message'=>"success",
                "dataLokasi" => $dataLokasi
            );

        } 
     
        echo json_encode($json);

    }

    function daftarLayananKB()
    {
        $user_id       = secure_input($this->input->post('user_id'));
        $tokenLogin    = secure_input($this->input->post('tokenLogin'));
        $nama         = secure_input($this->input->post('nama'));
        $nohp          = secure_input($this->input->post('nohp'));
        $noktp         = secure_input($this->input->post('noktp'));
        $address      = secure_input($this->input->post('address'));
        $alamatEmail      = secure_input($this->input->post('alamatEmail'));
        $bpjs         = secure_input($this->input->post('bpjs'));
        $daftarIva      = secure_input($this->input->post('daftarIva'));
        $lokasiKb      = secure_input($this->input->post('lokasiKb'));
        $jenisKb      = secure_input($this->input->post('jenisKb'));


     
        $checkNoKtp = $this->model->checkUserActive(array('user_id'=>$user_id),$tokenLogin);

        if($checkNoKtp->num_rows() < 1)
        {
            $json = array('status'=>201, 'message'=>"data anda tidak terdaftar / akun tidak aktif");

        }else 
        {



            $getIdLokasiKb = $this->model->selectWhere('mstlokasipelayanan',array('nama_lokasi' => $lokasiKb))->row();
            $getIdJenisKb = $this->model->selectWhere('msttipekb',array('nama_tipe' => $jenisKb))->row();

            $dataInsert = array(
                'id_pelayanan' => "1",
                'status_pendaftaran' => "1",
                'user_id' => $user_id,
                'no_ktp' => $noktp,
                'nama_lengkap' => $nama,
                'alamat' => $address,
                'email' => $alamatEmail,
                'no_bpjs' => $bpjs,
                'no_telp' => $nohp,
                'iva_test' => $daftarIva,
                'register_date' => date('Y-m-d H:i:s'),
                'tipe_kb' => $getIdJenisKb->tipekb_id,
                'lokasipelayanan_id' => $getIdLokasiKb->lokasipelayanan_id
            );
            $data = $this->model->insert('reg_pelayanan', $dataInsert);
            $json = array(
                'status'=>200, 
                'message'=>"berhasil"
            );

        } 
     
        echo json_encode($json);
    }

 

     function getDataPelayananPesertaBaru()
    {
        $user_id          = secure_input($this->input->post('user_id'));
        $tokenLogin         = secure_input($this->input->post('tokenLogin'));

        $checkNoKtp = $this->model->checkUserActive(array('user_id'=>$user_id),$tokenLogin);

        if($checkNoKtp->num_rows() < 1)
        {
            $json = array('status'=>201, 'message'=>"data anda tidak terdaftar / akun tidak aktif");

        }else 
        {
            $dataReg = $this->model->getDataRegisterLayananBaru();
            $arrData = array();
            foreach ($dataReg->result_array() as $key) {

                $var['id']    = $key['id_reg_pelayanan'];
                $var['nama_lengkap']    = $key['nama_lengkap'];
                $var['iva_test']        = $key['iva_test'] == "1" ? "Daftar IVA Test" : "Tidak Mendaftar IVA Test";
                $var['register_date']   = date('d-M-Y',strtotime($key['register_date']));
                $var['tipe_kb']         = $key['nama_tipe'];
                $var['lokasi_layanan'] = $key['nama_lokasi'];

                array_push($arrData, $var);
            }
        $json = array('status' => 200, 'message' => 'sukses', 'data' => $arrData);

        } 

     
        echo json_encode($json);
    }

    function dataStatusDaftar()
    {
        $user_id          = secure_input($this->input->post('user_id'));
        $tokenLogin         = secure_input($this->input->post('tokenLogin'));

     
        $checkNoKtp = $this->model->checkUserActive(array('user_id'=>$user_id),$tokenLogin);

        if($checkNoKtp->num_rows() < 1)
        {
            $json = array('status'=>201, 'message'=>"data anda tidak terdaftar / akun tidak aktif");

        }else 
        {
            $dataReg = $this->model->selectWhere('reg_pelayanan',array('user_id'=>$user_id))->row_array();
            $namaLengkap = $dataReg['nama_lengkap'];
            $tglDaftar = $this->tanggalIndo(date('Y-m-d',strtotime($dataReg['register_date'])));
            $statusDaftar = $dataReg['status_pendaftaran'];

            switch ($statusDaftar) {
                case '1': $statusDaftar = "Pending"; break;
                case '2': $statusDaftar = "Diproses"; break;
                case '3': $statusDaftar = "Selesai"; break;
                case '4': $statusDaftar = "Ditolak"; break;
            }


            $json = array('status' => 200, 'message' => 'sukses'
                    , 'namaLengkap' => $namaLengkap
                    , 'statusDaftar' => $statusDaftar
                    , 'tglDaftar' => $tglDaftar);

        } 

     
        echo json_encode($json);
    }

   

}
