 <?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Imageslider extends CI_Controller{
    function __construct()
    {
        parent::__construct(); 
        if (!$this->session->userdata('login')) {
            redirect('login','index');
        }
        $this->load->model('M_imageslider');
    } 

    /*
     * Listing of image_slider
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('imageslider/index?');
        $config['total_rows'] = $this->M_imageslider->get_all_image_slider_count();
        $this->pagination->initialize($config);

        $data['image_slider'] = $this->M_imageslider->get_all_image_slider($params);
        
        $data['_view'] = 'image_slider/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new image_banner
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   

                $image = time().'-'.str_replace(' ', '_', $_FILES["userfile"]['name']);

                $config = array(
                    'upload_path' => "./upload/images/",
                    'allowed_types' => "gif|jpg|png|jpeg|JPEG|JPG|PNG|GIF",
                    'overwrite' => TRUE,
                    'max_size' => "99999999999",
                    // 'max_height' => "800",
                    // 'max_width' => "1500",
                    'file_name' => $image
                    );
                    $this->load->library('upload', $config);

                if ( ! $this->upload->do_upload('userfile'))
                {
                        $error = array('error' => $this->upload->display_errors());
                                    $this->session->set_flashdata('Message',$error);
                        $data['_view'] = 'image_slider/add';
                        $this->load->view('layouts/main',$data);
                }
                else
                {
                        $data = array('upload_data' => $this->upload->data());
                        $params = array(
                            'slider_url' => base_url()."upload/imageslider/".$image,
                            'slider_file_name' => $image,
                            'created_at' => date('Y-m-d H:i:s'),
                            'created_by' => $this->session->userdata('admin_id'),
                            'start_date' => date('Y-m-d',strtotime($this->input->post('start_date')))." 00:00:00",
                            'end_date' => date('Y-m-d',strtotime($this->input->post('end_date')))." 23:59:59",
                            'active_status' => "1",
                        );
                        print_r($params); die;
                        
                        $image_banner_id = $this->M_imageslider->add_image_banner($params);
                        redirect('imageslider/index');

                }


            
        }
        else
        {            
            $data['_view'] = 'image_slider/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a image_banner
     */
    function edit($slider_id)
    {   
        // check if the image_banner exists before trying to edit it
        $data['image_banner'] = $this->M_imageslider->get_image_banner($slider_id);
        
        if(isset($data['image_banner']['slider_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   


                if(trim($_FILES["userfile"]['name']) != "")
                {

                         $image = time().'-'.str_replace(' ', '_', $_FILES["userfile"]['name']);

                            $config = array(
                                'upload_path' => "./upload/imageslider/",
                                'allowed_types' => "gif|jpg|png|jpeg|JPEG|JPG|PNG|GIF",
                                'overwrite' => TRUE,
                                'max_size' => "99999999999",
                                // 'max_height' => "800",
                                // 'max_width' => "1500",
                                'file_name' => $image
                                );
                                $this->load->library('upload', $config);

                            if ( ! $this->upload->do_upload('userfile'))
                            {
                                    $error = array('error' => $this->upload->display_errors());
                                    $this->session->set_flashdata('Message',$error);
                                    $data['_view'] = 'image_slider/edit';
                                    $this->load->view('layouts/main',$data);
                            }
                            else
                            {
                                    $data = array('upload_data' => $this->upload->data());
                                    $params = array(
                                        'slider_url' => base_url()."upload/imageslider/".$image,
                                        'slider_file_name' => $image,
                                        'created_by' => $this->session->userdata('admin_id'),
                                        'start_date' => date('Y-m-d',strtotime($this->input->post('start_date')))." 00:00:00",
                                        'end_date' => date('Y-m-d',strtotime($this->input->post('end_date')))." 23:59:59",
                                        'active_status' => "1",
                                    );
                                    
                                $this->M_imageslider->update_image_banner($slider_id,$params);            
                                redirect('imageslider/index');

                            }

                }else
                {
                   $params = array(
                        'created_by' => $this->session->userdata('admin_id'),
                        'start_date' => date('Y-m-d',strtotime($this->input->post('start_date')))." 00:00:00",
                        'end_date' => date('Y-m-d',strtotime($this->input->post('end_date')))." 23:59:59",
                        'active_status' => $this->input->post('active_status'),
                    ); 
                $this->M_imageslider->update_image_banner($slider_id,$params);            
                redirect('imageslider/index');
                }


                

            }
            else
            {
                $data['_view'] = 'image_slider/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The image_banner you are trying to edit does not exist.');
    } 

    /*
     * Deleting image_banner
     */
    function remove($slider_id)
    {
        $image_banner = $this->M_imageslider->get_image_banner($slider_id);

        // check if the image_banner exists before trying to delete it
        if(isset($image_banner['slider_id']))
        {
            $this->M_imageslider->delete_image_banner($slider_id);
            redirect('imageslider/index');
        }
        else
            show_error('The image_banner you are trying to delete does not exist.');
    }
    
}
