<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Jadwalpelayanantetap extends CI_Controller{
    function __construct()
    {
        parent::__construct(); 
        if (!$this->session->userdata('login')) {
            redirect('login','index');
        }
        $this->load->model('M_jadwalpelayanantetap');
    } 

    /*
     * Listing of info_jadwalpelayanantetap
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('jadwalpelayanantetap/index?');
        $config['total_rows'] = $this->M_jadwalpelayanantetap->get_all_info_jadwalpelayanantetap_count();
        $this->pagination->initialize($config);

        $data['info_jadwalpelayanantetap'] = $this->M_jadwalpelayanantetap->get_all_info_jadwalpelayanantetap($params);
        
        $data['_view'] = 'jadwalpelayanantetap/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new info_jadwal_pelayanan_tetap
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('lokasipelayanan_id','Lokasipelayanan Id','required');
		$this->form_validation->set_rules('tanggal','Tanggal','required');
		$this->form_validation->set_rules('jam_mulai','Jam Mulai','required|max_length[5]');
		$this->form_validation->set_rules('jam_selesai','Jam Selesai','required|max_length[5]');
        $this->form_validation->set_rules('keterangan','Keterangan / Info','max_length[250]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'lokasipelayanan_id' => $this->input->post('lokasipelayanan_id'),
				'tanggal' => $this->input->post('tanggal'),
				'jam_mulai' => $this->input->post('jam_mulai'),
				'jam_selesai' => $this->input->post('jam_selesai'),
                'created_by'    => $this->session->userdata('admin_id'),
                'keterangan'    => $this->input->post('keterangan'),
                'created_at'    => date('Y-m-d H:i:s')
            );
            
            $info_jadwal_pelayanan_tetap_id = $this->M_jadwalpelayanantetap->add_info_jadwal_pelayanan_tetap($params);
            redirect('jadwalpelayanantetap/index');
        }
        else
        {
			$this->load->model('M_lokasipelayanan');
			$data['all_mstlokasipelayanan'] = $this->M_lokasipelayanan->get_all_mstlokasipelayanan();
            
            $data['_view'] = 'jadwalpelayanantetap/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a info_jadwal_pelayanan_tetap
     */
    function edit($info_jadwal_id)
    {   
        // check if the info_jadwal_pelayanan_tetap exists before trying to edit it
        $data['info_jadwal_pelayanan_tetap'] = $this->M_jadwalpelayanantetap->get_info_jadwal_pelayanan_tetap($info_jadwal_id);
        
        if(isset($data['info_jadwal_pelayanan_tetap']['info_jadwal_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('lokasipelayanan_id','Lokasipelayanan Id','required');
			$this->form_validation->set_rules('tanggal','Tanggal','required');
			$this->form_validation->set_rules('jam_mulai','Jam Mulai','required');
			$this->form_validation->set_rules('jam_selesai','Jam Selesai','required');
            $this->form_validation->set_rules('keterangan','Keterangan / Info','max_length[250]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'lokasipelayanan_id' => $this->input->post('lokasipelayanan_id'),
					'tanggal' => $this->input->post('tanggal'),
					'jam_mulai' => $this->input->post('jam_mulai'),
					'jam_selesai' => $this->input->post('jam_selesai'),
                    'created_by'    => $this->session->userdata('admin_id'),
                    'keterangan'    => $this->input->post('keterangan'),
                );

                $this->M_jadwalpelayanantetap->update_info_jadwal_pelayanan_tetap($info_jadwal_id,$params);            
                redirect('jadwalpelayanantetap/index');
            }
            else
            {
				$this->load->model('M_lokasipelayanan');
				$data['all_mstlokasipelayanan'] = $this->M_lokasipelayanan->get_all_mstlokasipelayanan();

                $data['_view'] = 'jadwalpelayanantetap/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The info_jadwal_pelayanan_tetap you are trying to edit does not exist.');
    } 

    /*
     * Deleting info_jadwal_pelayanan_tetap
     */
    function remove($info_jadwal_id)
    {
        $info_jadwal_pelayanan_tetap = $this->M_jadwalpelayanantetap->get_info_jadwal_pelayanan_tetap($info_jadwal_id);

        // check if the info_jadwal_pelayanan_tetap exists before trying to delete it
        if(isset($info_jadwal_pelayanan_tetap['info_jadwal_id']))
        {
            $this->M_jadwalpelayanantetap->delete_info_jadwal_pelayanan_tetap($info_jadwal_id);
            redirect('jadwalpelayanantetap/index');
        }
        else
            show_error('The info_jadwal_pelayanan_tetap you are trying to delete does not exist.');
    }
    
}
