 <?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Jenispelayanan extends CI_Controller{
    function __construct()
    {
        parent::__construct(); 
        if (!$this->session->userdata('login')) {
            redirect('login','index');
        }
        $this->load->model('M_jenispelayanan');
    } 

    /*
     * Listing of jenis_pelayanan
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('jenispelayanan/index?');
        $config['total_rows'] = $this->M_jenispelayanan->get_all_jenis_pelayanan_count();
        $this->pagination->initialize($config);

        $data['jenis_pelayanan'] = $this->M_jenispelayanan->get_all_jenis_pelayanan($params);
        
        $data['_view'] = 'jenispelayanan/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new jenis_pelayanan
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama_pelayanan','Nama Pelayanan','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nama_pelayanan' => $this->input->post('nama_pelayanan'),
				'created_at' => date('Y-m-d H:i:s'),
				'created_by' => $this->session->userdata('admin_id'),
            );
            
            $jenis_pelayanan_id = $this->M_jenispelayanan->add_jenis_pelayanan($params);
            redirect('jenispelayanan/index');
        }
        else
        {            
            $data['_view'] = 'jenispelayanan/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a jenis_pelayanan
     */
    function edit($id_pelayanan)
    {   
        // check if the jenis_pelayanan exists before trying to edit it
        $data['jenis_pelayanan'] = $this->M_jenispelayanan->get_jenis_pelayanan($id_pelayanan);
        
        if(isset($data['jenis_pelayanan']['id_pelayanan']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nama_pelayanan','Nama Pelayanan','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nama_pelayanan' => $this->input->post('nama_pelayanan'),
                'created_at' => date('Y-m-d H:i:s'),
                'created_by' => $this->session->userdata('admin_id'),
                );

                $this->M_jenispelayanan->update_jenis_pelayanan($id_pelayanan,$params);            
                redirect('jenispelayanan/index');
            }
            else
            {
                $data['_view'] = 'jenispelayanan/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The jenis_pelayanan you are trying to edit does not exist.');
    } 

    /*
     * Deleting jenis_pelayanan
     */
    function remove($id_pelayanan)
    {
        $jenis_pelayanan = $this->M_jenispelayanan->get_jenis_pelayanan($id_pelayanan);

        // check if the jenis_pelayanan exists before trying to delete it
        if(isset($jenis_pelayanan['id_pelayanan']))
        {
            $this->M_jenispelayanan->delete_jenis_pelayanan($id_pelayanan);
            redirect('jenispelayanan/index');
        }
        else
            show_error('The jenis_pelayanan you are trying to delete does not exist.');
    }
    
}
