<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Listkecamatan extends CI_Controller{
    function __construct()
    {
        parent::__construct(); 
        if (!$this->session->userdata('login')) {
            redirect('login','index');
        }
        $this->load->model('M_listkecamatan');
    } 

    /*
     * Listing of mstkecamatan
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('listkecamatan/index?');
        $config['total_rows'] = $this->M_listkecamatan->get_all_mstkecamatan_count();
        $this->pagination->initialize($config);

        $data['mstkecamatan'] = $this->M_listkecamatan->get_all_mstkecamatan($params);
        
        $data['_view'] = 'listkecamatan/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new kecamatan
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama_kecamatan','Nama Kecamatan','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nama_kecamatan' => $this->input->post('nama_kecamatan'),
            );
            
            $kecamatan_id = $this->M_listkecamatan->add_kecamatan($params);
            redirect('listkecamatan/index');
        }
        else
        {            
            $data['_view'] = 'listkecamatan/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a kecamatan
     */
    function edit($kecamatan_id)
    {   
        // check if the kecamatan exists before trying to edit it
        $data['kecamatan'] = $this->M_listkecamatan->get_kecamatan($kecamatan_id);
        
        if(isset($data['kecamatan']['kecamatan_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nama_kecamatan','Nama Kecamatan','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nama_kecamatan' => $this->input->post('nama_kecamatan'),
                );

                $this->M_listkecamatan->update_kecamatan($kecamatan_id,$params);            
                redirect('listkecamatan/index');
            }
            else
            {
                $data['_view'] = 'listkecamatan/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The kecamatan you are trying to edit does not exist.');
    } 

    /*
     * Deleting kecamatan
     */
    function remove($kecamatan_id)
    {
        $kecamatan = $this->M_listkecamatan->get_kecamatan($kecamatan_id);

        // check if the kecamatan exists before trying to delete it
        if(isset($kecamatan['kecamatan_id']))
        {
            $this->M_listkecamatan->delete_kecamatan($kecamatan_id);
            redirect('listkecamatan/index');
        }
        else
            show_error('The kecamatan you are trying to delete does not exist.');
    }
    
}
