<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Login extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('useradmin_model','model');
        
    }

    function index()
    {
        $data['_view'] = 'login';
        $this->load->view('login',$data);
    }

    function auth()
    {
    		$email 		= secure_input($this->input->post('email'));
    		$password 	= secure_input($this->input->post('password'));
    		$password 	= md5($password);


			$rs = $this->model->checkUser($email, $password);

			if($rs)
			{
				foreach ($rs as $row) {

					if ($row->active_status == 1) {

						$this->session->set_userdata('login', true);
						$this->session->set_userdata('admin_id', $row->admin_id);
						$this->session->set_userdata('full_name', $row->full_name);
						$this->session->set_userdata('level_akses', $row->level_akses);
						$this->session->set_userdata('unit_id', $row->unit_id);

						$menu = $this->model->getUserMenu($row->level_akses)->result_array();
						$this->session->set_userdata('menu', $menu);
						
	     				redirect('/dashboard', 'refresh');
					}else
					{

						$this->session->set_flashdata('Message','user tidak aktif');
			        	$data['_view'] = 'login';
			       		$this->load->view('login',$data);
					}
				}
			}else
			{
				$this->session->set_flashdata('Message','Email / password salah');
	        	$data['_view'] = 'login';
	       		$this->load->view('login',$data);
			}
    }
    function logout()
    {

    	 session_destroy();
	     redirect('/login', 'refresh');
    }
}
