 <?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Lokasipelayanan extends CI_Controller{
    function __construct()
    {
        parent::__construct(); 
        if (!$this->session->userdata('login')) {
            redirect('login','index');
        }
        $this->load->model('M_lokasipelayanan');
    } 

    /*
     * Listing of mstlokasipelayanan
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('lokasipelayanan/index?');
        $config['total_rows'] = $this->M_lokasipelayanan->get_all_mstlokasipelayanan_count();
        $this->pagination->initialize($config);

        $data['mstlokasipelayanan'] = $this->M_lokasipelayanan->get_all_mstlokasipelayanan($params);
        
        $data['_view'] = 'lokasipelayanan/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new lokasi_pelayanan
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('kecamatan_id','Kecamatan Id','required');
		$this->form_validation->set_rules('nama_lokasi','Nama Lokasi','required');
		// $this->form_validation->set_rules('desa_id','Desa Id','required');
		
		if($this->form_validation->run())     
        {   

            $tipekb = $this->input->post('tipekb');
            $params = array(
				'kecamatan_id' => $this->input->post('kecamatan_id'),
				'nama_lokasi' => $this->input->post('nama_lokasi'),
            );
            
            $lokasi_pelayanan_id = $this->M_lokasipelayanan->add_lokasi_pelayanan($params);

            for ($i=0; $i < count($tipekb); $i++) { 
                  $params2 = array(
                    'lokasipelayanan_id' => $lokasi_pelayanan_id,
                    'tipekb_id' => $tipekb[$i],
                );
                
                $this->M_lokasipelayanan->add_layanankb($params2);
            }

            redirect('lokasipelayanan/index');
        }
        else
        {
			$this->load->model('M_listkecamatan');
			$data['all_mstkecamatan'] = $this->M_listkecamatan->get_all_mstkecamatan();

             $this->load->model('Msttipekb_model');
                $data['all_tipekb'] = $this->Msttipekb_model->get_all_msttipekb();

			$this->load->model('Mstdesa_model');
			$data['all_mstdesa'] = $this->Mstdesa_model->get_all_mstdesa();
            
            $data['_view'] = 'lokasipelayanan/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a lokasi_pelayanan
     */
    function edit($lokasipelayanan_id)
    {   
        // check if the lokasi_pelayanan exists before trying to edit it
        $data['lokasi_pelayanan'] = $this->M_lokasipelayanan->get_lokasi_pelayanan($lokasipelayanan_id);
        
        if(isset($data['lokasi_pelayanan']['lokasipelayanan_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('kecamatan_id','Kecamatan Id','required');
			$this->form_validation->set_rules('nama_lokasi','Nama Lokasi','required');
			// $this->form_validation->set_rules('desa_id','Desa Id','required');
		
			if($this->form_validation->run())     
            {   
            $tipekb = $this->input->post('tipekb');
                $params = array(
					'kecamatan_id' => $this->input->post('kecamatan_id'),
					// 'desa_id' => $this->input->post('desa_id'),
					'nama_lokasi' => $this->input->post('nama_lokasi'),
                );

                $this->M_lokasipelayanan->update_lokasi_pelayanan($lokasipelayanan_id,$params);
                $this->M_lokasipelayanan->delete_lokasidanjeniskb($lokasipelayanan_id);

                for ($i=0; $i < count($tipekb); $i++) { 
                      $params2 = array(
                        'lokasipelayanan_id' => $lokasipelayanan_id,
                        'tipekb_id' => $tipekb[$i],
                    );
                    
                    $this->M_lokasipelayanan->add_layanankb($params2);
                }

                redirect('lokasipelayanan/index');
            }
            else
            {
				$this->load->model('M_listkecamatan');
				$data['all_mstkecamatan'] = $this->M_listkecamatan->get_all_mstkecamatan();


                $this->load->model('Msttipekb_model');
                $data['all_tipekb'] = $this->Msttipekb_model->get_all_msttipekb();
                $data['layanankb'] = $this->M_lokasipelayanan->get_layanan_kb($lokasipelayanan_id);


				$this->load->model('Mstdesa_model');
				$data['all_mstdesa'] = $this->Mstdesa_model->get_all_mstdesa();

                $data['_view'] = 'lokasipelayanan/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The lokasi_pelayanan you are trying to edit does not exist.');
    } 

    /*
     * Deleting lokasi_pelayanan
     */
    function remove($lokasipelayanan_id)
    {
        $lokasi_pelayanan = $this->M_lokasipelayanan->get_lokasi_pelayanan($lokasipelayanan_id);

        // check if the lokasi_pelayanan exists before trying to delete it
        if(isset($lokasi_pelayanan['lokasipelayanan_id']))
        {
            $this->M_lokasipelayanan->delete_lokasi_pelayanan($lokasipelayanan_id);
            redirect('lokasipelayanan/index');
        }
        else
            show_error('The lokasi_pelayanan you are trying to delete does not exist.');
    }
    
}
