<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Reg_pelayanan extends CI_Controller{
    function __construct()
    {
        parent::__construct(); 
        if (!$this->session->userdata('login')) {
            redirect('login','index');
        }
        $this->load->model('Reg_pelayanan_model');
    } 

    /*
     * Listing of reg_pelayanan
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('reg_pelayanan/index?');
        $config['total_rows'] = $this->Reg_pelayanan_model->get_all_reg_pelayanan_count();
        $this->pagination->initialize($config);

        $data['reg_pelayanan'] = $this->Reg_pelayanan_model->get_all_reg_pelayanan($params);
        
        $data['_view'] = 'reg_pelayanan/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new list_user_register_pelayanan
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_pelayanan' => $this->input->post('id_pelayanan'),
				'user_id' => $this->input->post('user_id'),
				'tipe_kb' => $this->input->post('tipe_kb'),
				'lokasipelayanan_id' => $this->input->post('lokasipelayanan_id'),
				'no_ktp' => $this->input->post('no_ktp'),
				'nama_lengkap' => $this->input->post('nama_lengkap'),
				'email' => $this->input->post('email'),
				'no_bpjs' => $this->input->post('no_bpjs'),
				'no_telp' => $this->input->post('no_telp'),
				'register_date' => $this->input->post('register_date'),
				'alamat' => $this->input->post('alamat'),
            );
            
            $list_user_register_pelayanan_id = $this->Reg_pelayanan_model->add_list_user_register_pelayanan($params);
            redirect('reg_pelayanan/index');
        }
        else
        {
			$this->load->model('M_jenispelayanan');
			$data['all_jenis_pelayanan'] = $this->M_jenispelayanan->get_all_jenis_pelayanan();

			$this->load->model('M_userapps');
			$data['all_mstunit'] = $this->M_userapps->get_all_mstunit();

			$this->load->model('Msttipekb_model');
			$data['all_msttipekb'] = $this->Msttipekb_model->get_all_msttipekb();

			$this->load->model('M_lokasipelayanan');
			$data['all_mstlokasipelayanan'] = $this->M_lokasipelayanan->get_all_mstlokasipelayanan();
            
            $data['_view'] = 'reg_pelayanan/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a list_user_register_pelayanan
     */
    function edit($id_reg_pelayanan)
    {   
        // check if the list_user_register_pelayanan exists before trying to edit it
        $data['list_user_register_pelayanan'] = $this->Reg_pelayanan_model->get_list_user_register_pelayanan($id_reg_pelayanan);
        
        if(isset($data['list_user_register_pelayanan']['id_reg_pelayanan']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'tipe_kb' => $this->input->post('tipe_kb'),
					'lokasipelayanan_id' => $this->input->post('lokasipelayanan_id'),
					'no_ktp' => $this->input->post('no_ktp'),
					'nama_lengkap' => $this->input->post('nama_lengkap'),
					'email' => $this->input->post('email'),
					'no_bpjs' => $this->input->post('no_bpjs'),
					'no_telp' => $this->input->post('no_telp'),
					'alamat' => $this->input->post('alamat'),
                    'status_pendaftaran' => $this->input->post('status_pendaftaran')
                );


                $this->Reg_pelayanan_model->update_list_user_register_pelayanan($id_reg_pelayanan,$params);            
                redirect('reg_pelayanan/index');
            }
            else
            {
				$this->load->model('M_jenispelayanan');
				$data['all_jenis_pelayanan'] = $this->M_jenispelayanan->get_all_jenis_pelayanan();

				$this->load->model('M_userapps');
				$data['all_mstunit'] = $this->M_userapps->get_all_mstunit();

				$this->load->model('Msttipekb_model');
				$data['all_msttipekb'] = $this->Msttipekb_model->get_all_msttipekb();

				$this->load->model('M_lokasipelayanan');
				$data['all_mstlokasipelayanan'] = $this->M_lokasipelayanan->get_all_mstlokasipelayanan();

                $data['_view'] = 'reg_pelayanan/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The list_user_register_pelayanan you are trying to edit does not exist.');
    } 

    /*
     * Deleting list_user_register_pelayanan
     */
    function remove($id_reg_pelayanan)
    {
        $list_user_register_pelayanan = $this->Reg_pelayanan_model->get_list_user_register_pelayanan($id_reg_pelayanan);

        // check if the list_user_register_pelayanan exists before trying to delete it
        if(isset($list_user_register_pelayanan['id_reg_pelayanan']))
        {
            $this->Reg_pelayanan_model->delete_list_user_register_pelayanan($id_reg_pelayanan);
            redirect('reg_pelayanan/index');
        }
        else
            show_error('The list_user_register_pelayanan you are trying to delete does not exist.');
    }
    
}
