<?php
ini_set('post_max_size', '64M');
ini_set('upload_max_filesize', '64M');
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sekilasinfo extends CI_Controller{
    function __construct()
    {
        parent::__construct(); 
        if (!$this->session->userdata('login')) {
            redirect('login','index');
        }
        $this->load->model('M_sekilasinfo');
    } 

    /*
     * Listing of mstinfo
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('sekilasinfo/index?');
        $config['total_rows'] = $this->M_sekilasinfo->get_all_mstinfo_count();
        $this->pagination->initialize($config);

        $data['mstinfo'] = $this->M_sekilasinfo->get_all_mstinfo($params);
        
        $data['_view'] = 'sekilasinfo/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new news__info
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('info_title','Info Title','required');
		$this->form_validation->set_rules('info_desc','Info Desc','required');
        $this->form_validation->set_rules('info_summary','Sumary Artikel','required|max_length[200]');
		
		if($this->form_validation->run())     
        {   

            $image = time().'-'.str_replace(' ', '_', $_FILES["userfile"]['name']);

                $config = array(
                    'upload_path' => "./upload/images/",
                    'allowed_types' => "gif|jpg|png|jpeg|JPEG|JPG|PNG|GIF",
                    'overwrite' => TRUE,
                    'max_size' => "99999999999",
                    'file_name' => $image
                    );
                    $this->load->library('upload', $config);

                if ( ! $this->upload->do_upload('userfile'))
                {
                        $error = array('error' => $this->upload->display_errors());
                        $data['_view'] = 'sekilasinfo/add';
                        $this->load->view('layouts/main',$data);
                }
                else
                {
                        $data = array('upload_data' => $this->upload->data());
                        $params = array(
                            'image_url' => base_url()."upload/images/".$image,
                            'info_title' => $this->input->post('info_title'),
                            'info_summary' => $this->input->post('info_summary'),
                            'created_by' => $this->session->userdata('admin_id'),
                            'created_at' => date('Y-m-d H:i:s'),
                            'active_status' => "1",
                            'info_desc' => $this->input->post('info_desc')
                        );
                        
                        $news__info_id = $this->M_sekilasinfo->add_news__info($params);
                        redirect('sekilasinfo/index');

                }

            
        }
        else
        {            
            $data['_view'] = 'sekilasinfo/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a news__info
     */
    function edit($info_id)
    {   
        // check if the news__info exists before trying to edit it
        $data['news__info'] = $this->M_sekilasinfo->get_news__info($info_id);
        
        if(isset($data['news__info']['info_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('info_title','Info Title','required');
			$this->form_validation->set_rules('info_desc','Info Desc','required');
        $this->form_validation->set_rules('info_summary','Sumary Artikel','required|max_length[200]');
		
			if($this->form_validation->run())     
            {   

                      if(trim($_FILES["userfile"]['name']) != "")
                {

                         $image = time().'-'.str_replace(' ', '_', $_FILES["userfile"]['name']);

                            $config = array(
                                'upload_path' => "./upload/images/",
                                'allowed_types' => "gif|jpg|png|jpeg|JPEG|JPG|PNG|GIF",
                                'overwrite' => TRUE,
                                'max_size' => "99999999999",
                                // 'max_height' => "800",
                                // 'max_width' => "1500",
                                'file_name' => $image
                                );
                                $this->load->library('upload', $config);

                            if ( ! $this->upload->do_upload('userfile'))
                            {
                                    $error = array('error' => $this->upload->display_errors());
                                    $this->session->set_flashdata('Message',$error);
                                    $data['_view'] = 'sekilasinfo/edit';
                                    $this->load->view('layouts/main',$data);
                            }
                            else
                            {
                                    $data = array('upload_data' => $this->upload->data());
                                    $params = array(
                                        'image_url' => base_url()."upload/images/".$image,
                                        'info_title' => $this->input->post('info_title'),
                                        'info_summary' => $this->input->post('info_summary'),
                                        'created_by' => $this->session->userdata('admin_id'),
                                        'active_status' => $this->input->post('active_status'),
                                        'info_desc' => $this->input->post('info_desc'),
                                    );
                                    

                                $this->M_sekilasinfo->update_news__info($info_id,$params);            
                                redirect('sekilasinfo/index');

                            }

                }else
                {
                    $params = array(
                        'info_title' => $this->input->post('info_title'),
                        'created_by' => $this->session->userdata('admin_id'),
                        'active_status' => $this->input->post('active_status'),
                        'info_summary' => $this->input->post('info_summary'),
                        'info_desc' => $this->input->post('info_desc'),
                    );

                    $this->M_sekilasinfo->update_news__info($info_id,$params);            
                    redirect('sekilasinfo/index');
                }

            }
            else
            {
                $data['_view'] = 'sekilasinfo/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The news__info you are trying to edit does not exist.');
    } 

    /*
     * Deleting news__info
     */
    function remove($info_id)
    {
        $news__info = $this->M_sekilasinfo->get_news__info($info_id);

        // check if the news__info exists before trying to delete it
        if(isset($news__info['info_id']))
        {
            $this->M_sekilasinfo->delete_news__info($info_id);
            redirect('sekilasinfo/index');
        }
        else
            show_error('The news__info you are trying to delete does not exist.');
    }
    
}
