<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_history_pelayanan extends CI_Controller{
    function __construct()
    {
        parent::__construct(); 
        if (!$this->session->userdata('login')) {
            redirect('login','index');
        }
        $this->load->model('User_history_pelayanan_model');
    } 

    /*
     * Listing of user_history_pelayanan
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        

        $data['user_history_pelayanan'] = $this->User_history_pelayanan_model->get_all_user_history_pelayanan($params);
        
        $data['_view'] = 'user_history_pelayanan/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new historis_pelayanan
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'user_id' => $this->input->post('user_id'),
				'lokasipelayanan_id' => $this->input->post('lokasipelayanan_id'),
				'id_pelayanan' => $this->input->post('id_pelayanan'),
				'history_datetime' => date('Y-m-d H:i:s'),
				'text_keluhan' => $this->input->post('text_keluhan'),
				'text_tindakan' => $this->input->post('text_tindakan'),
            );
            
            $historis_pelayanan_id = $this->User_history_pelayanan_model->add_historis_pelayanan($params);
            redirect('user_history_pelayanan/index');
        }
        else
        {
			$this->load->model('M_userapps');
			$data['all_mstunit'] = $this->M_userapps->get_all_mstunit();

			$this->load->model('M_lokasipelayanan');
			$data['all_mstlokasipelayanan'] = $this->M_lokasipelayanan->get_all_mstlokasipelayanan();

			$this->load->model('M_jenispelayanan');
			$data['all_jenis_pelayanan'] = $this->M_jenispelayanan->get_all_jenis_pelayanan();
            
            $data['_view'] = 'user_history_pelayanan/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a historis_pelayanan
     */
    function edit($id_history)
    {   
        // check if the historis_pelayanan exists before trying to edit it
        $data['historis_pelayanan'] = $this->User_history_pelayanan_model->get_historis_pelayanan($id_history);
        
        if(isset($data['historis_pelayanan']['id_history']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'user_id' => $this->input->post('user_id'),
					'lokasipelayanan_id' => $this->input->post('lokasipelayanan_id'),
					'id_pelayanan' => $this->input->post('id_pelayanan'),
					'text_keluhan' => $this->input->post('text_keluhan'),
					'text_tindakan' => $this->input->post('text_tindakan'),
                );

                $this->User_history_pelayanan_model->update_historis_pelayanan($id_history,$params);            
                redirect('user_history_pelayanan/index');
            }
            else
            {
				$this->load->model('M_userapps');
				$data['all_mstunit'] = $this->M_userapps->get_all_mstunit();

				$this->load->model('M_lokasipelayanan');
				$data['all_mstlokasipelayanan'] = $this->M_lokasipelayanan->get_all_mstlokasipelayanan();

				$this->load->model('M_jenispelayanan');
				$data['all_jenis_pelayanan'] = $this->M_jenispelayanan->get_all_jenis_pelayanan();

                $data['_view'] = 'user_history_pelayanan/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The historis_pelayanan you are trying to edit does not exist.');
    } 

    /*
     * Deleting historis_pelayanan
     */
    function remove($id_history)
    {
        $historis_pelayanan = $this->User_history_pelayanan_model->get_historis_pelayanan($id_history);

        // check if the historis_pelayanan exists before trying to delete it
        if(isset($historis_pelayanan['id_history']))
        {
            $this->User_history_pelayanan_model->delete_historis_pelayanan($id_history);
            redirect('user_history_pelayanan/index');
        }
        else
            show_error('The historis_pelayanan you are trying to delete does not exist.');
    }
    
}
